### ISSUE TITLE
Icon does not show in Iceweasel browser

### ISSUE THREAD

**Issue by RubberChickenz** [reezer/tor-flashproxy-badge#14]
Hello!  I only have this add-on installed, and have enabled Javascript in the browser options.  No icon (green, red, or otherwise) is appearing, even after restarting Iceweasel.
![2014-02-20--1392935933_953x486_scrot](https://f.cloud.github.com/assets/6742441/2224546/2a4739b4-9a80-11e3-9603-ad42391fbf53.png)

**Comment by reezer** [comment]
Closing, because there was no feedback in years.
