### ISSUE TITLE
I am running the latest firefox where do i see the green/colored dot?

### ISSUE THREAD

**Issue by MasterDanman** [reezer/tor-flashproxy-badge#17]
I am running the latest firefox where do i see the green/colored dot? Can u tell me where

**Comment by reezer** [comment]
Can you go into the Add-ons Manager, select Extensions on the left, click on the gear on top right corner, next to the Search Box and select "Check for Updates". A new version was released and when you update the dot should appear next to the other Add-on icon.

**Comment by MasterDanman** [comment]
Thx it worked!

   *Daniel R. Cote*

The content of this email is confidential and is intended to be read only
by named recipient. Unauthorized disclosure, copying, distribution or
actions based on its content are prohibited. If you are not the named
recipient, please notify the sender immediately and delete this message
from your mail system.
