### ISSUE TITLE
Ridiculous description

### ISSUE THREAD

**Issue by chefarov** [reezer/tor-flashproxy-badge#18]
"Installing this addon allows your browser to become a bridge for censored internet users, like in China, Iran or Syria"

Like coming from White house, or FOX news. Saudi Arabia, Bahrain, Colombia are ok, but the dictators live only in BRICS countries lol.

The moment we speak, Internet in France is more restrictive than in Syria, following the terror attack. If anyone just takes a moment to think, Syria has experienced 5 years of terrorism, thus if they took more censorship measuses after every attack, there would be no internet at all by now... :D

**Comment by reezer** [comment]
While I agree with you on the political side I wanted to have a basic description and not make a political statement (Syria was added before the emergence of violence some years ago - at least from the information I had). Therefor if you have a better description please feel free to make a pull request. My only request is to not have it be too long and maybe not overly political.

The list of mentioned countries mentioned is based off countries that actually block. Of course it might also be individual ISPs or organizations (I hear the NSA and some military institutions) blocking for example access to news portals.

This add-on's purpose is to allow people to to circumvent censorship (to the Tor network). The description actually is targeted at ordinary people who frequently don't have a lot of insight. It wasn't my intention to be one-sided, so as I said, please feel free to make a pull request with a more complete list of potential users.

You could even make an own section of censorship or maybe we can include a link to something like Wikipedia or other/better places give examples. 

Thanks for your input! :)

I'd welcome any pull request that is somewhat politically neutral, after all I don't want this to be censored on its own.
